### ISSUE TITLE
Failed to create FFmpeg pipe `writer->WriteFrame` failed. The FramePool will close.

### ISSUE THREAD

**Issue by josevmorilla** [cademtz/sparkly-fx#6]
**Failed to create FFmpeg pipe
`writer->WriteFrame` failed. The FramePool will close.**

![issue](https://github.com/cademtz/sparkly-fx/assets/142756582/cd3e8c3b-69cf-435e-9048-b85247f245c2)

FFmpeg doesnt seem to record the frames and it gives me an "audio" file of only one frame with no output
![image](https://github.com/cademtz/sparkly-fx/assets/142756582/e9519d05-e18c-4523-92f6-fedd5e3cad6f)

**Comment by cademtz** [comment]
Please attach your config file and I will look into this

**Comment by josevmorilla** [comment]
[cfg.zip](https://github.com/cademtz/sparkly-fx/files/15380948/cfg.zip)

**Comment by cademtz** [comment]
I'm sorry, I meant for you to attach Sparkly FX's config file.

You can find this next to xsd-base64.dll file, in`sparklyfx/config.json`

**Comment by cademtz** [comment]
In the meantime, try a different directory. It is possible that your game does not have permission to write frames to `E:\Sparkly`

EDIT: Nevermind. This does not apply to you because FFmpeg would have printed the following:
```
Failed to create folder (Access is denied.): 'C:\'
```

**Comment by cademtz** [comment]
A new update was released. It will reveal more detailed information in the error log.

You can test the update and see what the new errors look like.

**Comment by josevmorilla** [comment]
It still seems to give me the same error when I press play on sparklyfx, I updated to the latest build but it doesnt seem to give me more info on the error log. 
Config:
[config.json](https://github.com/cademtz/sparkly-fx/files/15428150/config.json)
![failed ffmpeg](https://github.com/cademtz/sparkly-fx/assets/142756582/74fe0eed-6a75-4d35-82ae-6629abc15bce)


I have hlae launcher with the newest patch
![image](https://github.com/cademtz/sparkly-fx/assets/142756582/0b0bc3cd-7f56-4bd9-9a8c-e94628ff8436)
![image](https://github.com/cademtz/sparkly-fx/assets/142756582/4db2b73e-a159-41f8-a4f0-59162ac1c310)

**Comment by josevmorilla** [comment]
[xsdk-crashlog.txt](https://github.com/cademtz/sparkly-fx/files/15428263/xsdk-crashlog.txt)

crash log

**Comment by Uryyb4** [comment]
I'm having the same issue, [heres my config](https://github.com/cademtz/sparkly-fx/files/15491808/config.json)

If anybody else runs into this issue, just specify qoi as sparklyfx's video encoder, then use `-framerate yourfps -pattern_type sequence -i frame_%d.qoi` in the output folder of sparklyfx with ffmpeg, along with any other encoding settings

**Comment by cademtz** [comment]
@Uryyb4 @esogcs I have found the likely issue. SparklyFX only uses the default FFmpeg path, and *not* the one you manually specified. For esogcs and another users, no default FFmpeg path existed.

This behavior is obviously incorrect and will be fixed shortly.

**Comment by cademtz** [comment]
Should be fixed in commit f1965c9da47ea2e171d897ff075917f4c7f1a409.
Please download the latest release and confirm this for me, when you have time.

**Comment by josevmorilla** [comment]
works now, thank you
